### PR TITLE
Issue1016-SendQuoteRequestsToReproduceBugs

### PR DESCRIPTION
**Pull request by gibaros**
Issue1016-SendQuoteRequestsToReproduceBugs

### CODE REVIEW

**Comment by gibaros** [comment]
@elnyry Conflict was resolved 4 days ago, anything else needed here?

**Comment by elnyry** [comment]
> @elnyry Conflict was resolved 4 days ago, anything else needed here?

@gibaros we discussed offline, changes and refactoring needed here. I'm not sure if thats done.. If so, then yeah we can review it again..

**Comment by amarmodus** [comment]
@gibaros - could you please ensure all refactoring done as per Sam's findings? 
Many tests are failing and appropriate tests needs to be added. (eg. checking error code and error description if we expect error due to invalid content type and so on)

**Comment by amarmodus** [comment]
@gibaros - I will take over this PR and do further changes required.

**Comment by amarmodus** [comment]
https://github.com/mojaloop/postman/pull/67 replaces this

**Pull request closed without merging**
