### PR TITLE
Feature/sm als tests

### PR DESCRIPTION
**Pull request by sri-miriyala**
Added Oracle API tests. Updated /parties /participants endpoints.

### CODE REVIEW

**Comment by elnyry** [comment]
@sri-miriyala Thanks for the PR.

I cloned this locally and tried to run the tests against the OSS dev2 envt and wasn't able to properly run it.

Are your changes included under the "Mojaloop-API" (parties , participants) or "ALS API" ? I also tried to run the "MSISDN Oracle", wasn't able to run it.

One other thing is that there are two Merchant-Oracle folders, can you please check which one is supposed to be there?

**Comment by sri-miriyala** [comment]
My tests are in Mojaloop-API for /participans and /parties. What errors did you get running them?

**Comment by elnyry** [comment]
References to interop-switch endpoint still present..

**Comment by elnyry** [comment]
@sri-miriyala can you please update the PR to now remove the Golden FSP collection as it is now merged via another PR?

As we discussed, please raise separate PRs for Fees, multi-currency tests on Settlements so that its easy to test and review.

Thanks for your work!

**Pull request closed without merging**
