### PR TITLE
Added 2 new collections to test golden path using mojaloop simulators

### PR DESCRIPTION
**Pull request by sri-miriyala**

### CODE REVIEW

**Comment by elnyry** [comment]
Looking forward to try these out on the perf envt..

**Comment by sri-miriyala** [comment]
Results:
Screen Shot 2019-11-28 at 12 51 15 AM

**Comment by sri-miriyala** [comment]
Screen Shot 2019-11-28 at 12 51 15 AM

**Comment by amarmodus** [comment]
could get following result in TIPS environment
image

**Pull request merged**
