### PR TITLE
Changes to Onboarding, removed FXP sims onboarding, renamed the…

### PR DESCRIPTION
**Pull request by sri-miriyala**
Few changes to onboarding... removed FXP sims onboarding, renamed the OSS_New_Deployment_FSP_Setup to "MojaloopSims_Onboarding"

### CODE REVIEW

**Comment by elnyry** [comment]
hi @sri-miriyala , one generic comment: I was thinking of the name for this and other collections and what do you think about "ML-Switch_Setup_MojaSims_Onboarding" as it includes setting up the Switch and onboarding Mojaloop Simulators?

If you agree, we can rename the others as relevant too.

**Comment by sri-miriyala** [comment]
@elnyry  am further separating Hub_setup scripts and moving to a different collection. So, we will have "Hub_InitialSetUp" and "MojaloopSims_onboarding".

**Comment by sri-miriyala** [comment]
@elnyry ... Separated into MojaloopHub_Setup and MojaloopSim_Onboarding as these are separate activities. Also added a new collection to get OAuth bearer token. This will not be applicable in OSS till wso2 is deployed, but will be used in other environments that has wso2.

**Comment by elnyry** [comment]
@sri-miriyala , thanks for the update..

**Pull request merged**
